### PR TITLE
Add json output

### PR DESCRIPTION
**Pull request by cyrinux**
Hi @xbglowx ,

Tiny PR to add json output.

Regards 🎄

### CODE REVIEW

**Review by xbglowx — COMMENTED** [review]
Not sure if it is just me, but it appears the output is incorrect. I don't have time to help you debug right now, but let me know if you are seeing the same bug?

I did a test with `bin/github.com/xbglowx/vault-kv-search -s secret/ https`

**Comment by cyrinux** [comment]
> Not sure if it is just me, but it appears the output is incorrect. I don't have time to help you debug right now, but let me know if you are seeing the same bug?
> 
> I did a test with `bin/github.com/xbglowx/vault-kv-search -s secret/ https`

Hey, I reverse some fields I fix the typos.
JSON look like this:
```
{"search":"value","path":"secret/users/user1","key":"user","value":"john"}
```

**Review by xbglowx — COMMENTED** [review]
LGTM.

Can you please squash your commits?

**Comment by cyrinux** [comment]
> LGTM.
> 
> Can you please squash your commits?

Done 😺

**Review by xbglowx — APPROVED** [review]

**Comment by xbglowx** [comment]
> > LGTM.
> > Can you please squash your commits?
> 
> Done 😺 By chance can you cut a release then ?

I just released [v0.1.0](https://github.com/xbglowx/vault-kv-search/releases/tag/v0.1.0).

**Pull request merged**
